krk_flights_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: "{{ env_var('BQ_DATASET_ID', 'krk_flights') }}"
      location: US
      threads: 4
      keyfile: /opt/airflow/creds/gcp-service-account.json
      job_execution_timeout_seconds: 300
      job_retries: 1
